export const CALENDAR_CONSTANTS = {
  LAYOUT: {
    TIME_COLUMN_WIDTH: 60,
    TIME_ROW_HEIGHT: 48,
    TASK_CHIP_HEIGHT: 24,
    ALL_DAY_HEADER_HEIGHT: 30,
    ALL_DAY_PADDING: 8,
    TASK_TOP_OFFSET: 4,
    TIME_SNAP_MINUTES: 15,
    MIN_DAYS: 1,
    MAX_DAYS: 14
  },

  PADDING: {
    COLUMN_PADDING: 5,
    TASK_PADDING: 4,
    MORE_BUTTON_PADDING: 8,
    CONTEXT_MENU_PADDING: 8
  },

  SPACING: {
    HOUR_CELL_LEFT_MARGIN: 5,
    CURRENT_TIME_LINE_LEFT: 5,
    CURRENT_TIME_LINE_MARGIN: 10,
    MORE_BUTTON_LEFT: 4,
    MORE_BUTTON_WIDTH_OFFSET: 16
  }
} as const;

export type CalendarConstants = typeof CALENDAR_CONSTANTS;
